# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gradient Rage
email: hinsonan@gmail.com
favicon: "/favicon.ico"
description: >- # this means to ignore newlines until "baseurl:"
  ML/Software Engineering is hard, people are dumb, and we're all just winging it with overpriced GPUs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gradientrage.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hinsonan
github_username:  hinsonan
author: Andrew Hinson

# SEO and social media
twitter:
  username: hinsonan
  card: summary_large_image

# LinkedIn optimization
linkedin:
  username: hinsonan

# Open Graph defaults (works for Facebook, LinkedIn, WhatsApp, etc.)
og:
  image: "/assets/images/robot.png"
  type: "website"

social:
  name: Andrew Hinson
  links:
    - https://x.com/hinsonan
    - https://github.com/hinsonan
    - https://linkedin.com/in/hinsonan

# Default meta tags for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Andrew Hinson"
      image: "/assets/images/robot.png"

# Build settings
# remote_theme: pages-themes/midnight
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Syntax highlighting configuration
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax

# Rouge configuration
rouge:
  # Available themes: base16, colorful, github, gruvbox, igor_pro, magritte, 
  # molokai, monokai, pastie, thankful_eyes, tulip
  theme: monokai  # Change this to your preferred theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CLAUDE.md
  - docker-compose.yaml
  - README.md
